### ISSUE TITLE
FeaturesViewModel is released immediately?

### ISSUE THREAD

**Issue by chatarveer** [growthbook/growthbook-swift#14]
**my code.**

```
@IBAction func initSDK(_ sender: Any) {
    let hostURL = "url_here"
    sdkInstance = GrowthBookBuilder(hostURL: hostURL,
                                    attributes: ["platform" : "iOS",
                                                 "country":"mafegy"],
                                    trackingCallback: { experiment, experimentResult in
    }).initializer()
  }
```

**Growthbook code**

```
    /// Manually Refresh Cache
    @objc public func refreshCache() {
        let featureVM = FeaturesViewModel(delegate: self, dataSource: FeaturesDataSource(dispatcher: networkDispatcher))
        featureVM.fetchFeatures(apiUrl: gbContext.hostURL)
    }

```

Here - FeaturesViewModel gets deinit 

`        dataSource.fetchFeatures(apiUrl: apiUrl) { [weak self] result in` 

**// here weak self is nil as deinit is being called weak self** 

Can you look into it? If I make **_let featureVM = FeaturesViewModel(_** global or remove weak self, it works fine. as scope ends for FeaturesViewModel.

<img width="1792" alt="CleanShot 2022-08-02 at 13 34 54@2x" src="https://user-images.githubusercontent.com/11245843/182343111-150cd515-8aa3-44e4-8872-0d575784fe2f.png">

**Comment by DNAlchemist** [comment]
Related https://github.com/growthbook/growthbook-swift/pull/15
@vazarkevych can someone take a look at this?
We have same problem

**Comment by vazarkevych** [comment]
@chatarveer thank you for creating the issue. I see you also created the MR to fix it. 
We've just merged your MR, thank you for that catch!
The new release version will be available soon.
