### ISSUE TITLE
How to convert GrowthBook.JSON to coddle models?

### ISSUE THREAD

**Issue by RajChanchal** [growthbook/growthbook-swift#22]
I want to convert GrowthBook.JSON to codable models. But I don't see anything like this in code. Could someone please help?

**Comment by vazarkevych** [comment]
Hello @RajChanchal,
Thank you for reaching out and bringing up the idea of converting GrowthBook.JSON to Codable models. It's a great suggestion that could potentially streamline our codebase.
However, after considering the complexity and size of GrowthBook.JSON, we find it's not feasible to directly convert it to Codable models at this time. The JSON object is quite large and involves a myriad of nested structures, which makes the task of manually creating Codable models highly error-prone and time-consuming.
That said, we are always looking for ways to improve our code and streamline our processes. If you have alternative suggestions or if you think there is a specific section that could benefit from this, we'd love to hear your thoughts.
Thank you for your understanding and cooperation.
