### ISSUE TITLE
'trackingCallback' is not being called despite that all settings are set from the dashboard 

### ISSUE THREAD

**Issue by sof9816** [growthbook/growthbook-swift#29]
```
var instance = GrowthBookBuilder(url: growthURL,
                                     attributes: attributes,
                                     trackingCallback: { experiment, experimentResult in
            print("Viewed Experiment")
            print("Experiment Id: ", experiment.key)
            print("Variation Id: ", experimentResult.variationId)

        })
        .initializer()
```
This is iOS code, yet neither android is running

**Comment by vazarkevych** [comment]
Hi @sof9816, thank you for the feedback. In order to receive a trackingCallback, you should call the function which runs experiments, for example: 
```swift
    instance.run(experiment: <Put here your experiment>)
```
Let me know if this helps

**Comment by sof9816** [comment]
This didn't help but apparently, we need to call a feature that has experiment using `evalFeature` and set `env` to `prod` as an attribute, at least that's what we did for now, anyway thanks for your reply.
