### ISSUE TITLE
Which version of the SDK spec is supported?

### ISSUE THREAD

**Issue by tikitu** [growthbook/growthbook-swift#31]
Hi folks, I couldn't see so easily which version of the [SDK spec](https://docs.growthbook.io/lib/build-your-own) is supposed by the latest release. If it's possible to add that information to subsequent releases it would make using your library easier (since we need to match spec versions across multiple platforms). In the meantime: which spec version is currently supported, in release 1.0.37?

**Comment by vazarkevych** [comment]
Hi @tikitu, thank you for your feedback. We have added information on the spec version to the ReadMe.

Version SDK 1.0.37 is the supposed version of the SDK spec v0.4.0 - v0.4.2

The latest version is our SDK 1.0.40 which is supposed v0.5.0 version of the SDK spec.
