### ISSUE TITLE
response 304 Not Modified

### ISSUE THREAD

**Issue by m3t8d1tr** [growthbook/growthbook-swift#40]
Request api/features/sdk-laxFrU33UrMаh8NK
Response 304 Not Modified

Hi there. 
Has anyone encountered such a response with GrowthBookBuilder?
Some kind of problem with the cache. There is no such situation on Android.

Thanks in advance.

**Comment by tinahollygb** [comment]
The server returns 304 Not Modified in browsers, and possibly other clients. It's expected that SDK's should handle a response from 304 responses. Is there a bug when a 304 response is received in the Swfit SDK? It still contains the features and it's expected that all SDK's parse the response data. Can you explain what issue you are seeing?

**Comment by m3t8d1tr** [comment]
I'm use proxyman for checking response from gb server and request sdk iOS. I'm not understand why response from Android(code 200) and iOS(code 304) is different?

**Comment by tinahollygb** [comment]
> I'm use proxyman for checking response from gb server and request sdk iOS. I'm not understand why response from Android(code 200) and iOS(code 304) is different?

@m3t8d1tr it's likely the underlying networking library used in the iOS SDK is sending relevant headers to say it's received the content, and the Android one is not. You can learn more about how the 304 Not Modified HTTP code works from the following resources:

- https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/304
- https://stackoverflow.com/a/20978279

When you get a 304, does the SDK still work or are you experiencing a bug with feature or experiment evaluation?

**Comment by m3t8d1tr** [comment]
@tinahollygb thank you, Tina. As far as I know, there is no bug from QA.
Last questions: It is possible to modify the header via SDK so as not to send `If-Modified-Since` or `If-None-Match` row?
