### ISSUE TITLE
FeaturesViewModel captures delegate as a strong reference

### ISSUE THREAD

**Issue by sapharow** [growthbook/growthbook-swift#45]
The `FeaturesViewModel` captures `delegate` as a strong reference causing circular reference (v1.0.44)

**Comment by vazarkevych** [comment]
Hello @sapharow,
Thank you for bringing this critical issue to our attention.
Your feedback has been invaluable in helping us improve the stability and functionality of our SDK. Please update to the latest version once it's available and let us know if the changes have resolved the issue or if you encounter any other problems.
