### ISSUE TITLE
Request visionOS support

### ISSUE THREAD

**Issue by loganblevins** [growthbook/growthbook-swift#51]

**Comment by vazarkevych** [comment]
Hello @loganblevins,
Thank you for requesting this new feature. We take a look at implementing it into the SDK and let you now know when it will be ready for use.

**Comment by loganblevins** [comment]
@vazarkevych I'd love to help push this forward. 

Please approve CI runners for my PR: https://github.com/growthbook/growthbook-swift/pull/52

**Comment by loganblevins** [comment]
@vazarkevych This can be closed if my PR #52 is approved + merged
