### ISSUE TITLE
Is there a way to implement a realtime feature listener?

### ISSUE THREAD

**Issue by MohadKadib** [growthbook/growthbook-swift#57]
i want to be able to toggle a feature on/off for all users at once, currently iam using the `refreshHandler` call back in the GrowthBookBuilder initialiser to listen on changes, whenever it is called i use the `isOn` function on all my feature keys that i want, but after some minutes in a session, it stops sending call backs in refreshHandler, why is that and is there a way to implement what i need?

**Comment by vazarkevych** [comment]
Hi, @MohadKadib. We've identified an issue with backgroundSync and have resolved it. Please try installing the latest release, version 53, which includes this fix.
