### ISSUE TITLE
Unable to find a specification for `GrowthBook-IOS`

### ISSUE THREAD

**Issue by wale-fingo** [growthbook/growthbook-swift#6]
After adding the dependency to Pod file according as stated in the `README.md` in-order to install the SDK via CocoaPods, I got the following error

```
[!] Unable to find a specification for `GrowthBook-IOS`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

**Comment by chatarveer** [comment]
@wale-fingo 

I used 

`pod 'GrowthBook'`

but cloned repo as dependency but didn't work as lots of renaming there.
