### ISSUE TITLE
Disable SSE Streaming in Mobile SDK

### ISSUE THREAD

**Issue by mattials** [growthbook/growthbook-swift#60]
Is there a way to disable Server-Sent Events (SSE) streaming in the GrowthBook Mobile SDK similar to how it can be done in browser environments?

Context
The documentation mentions enabling SSE streaming in browser environments by setting streaming: true in the initialization call. However, it's unclear if there's an equivalent method to disable SSE streaming in the Mobile SDK. https://docs.growthbook.io/lib/js/#streaming-in-browser-environments

Thank you for your assistance.

**Comment by mattials** [comment]
https://github.com/growthbook/growthbook-swift?tab=readme-ov-file#streaming-updates

**Comment by vazarkevych** [comment]
Hi, @mattials . Yes, by default, it is disabled(backgroundSync set to true). SSE will only work if you set backgroundSync to true. This is the way it works on Mobile SDK.

**Comment by mattials** [comment]
@vazarkevych SSE is enabled by default in mobile SDK?
