### ISSUE TITLE
[Bug] evalCondition ignores other conditions if special operator exists

### ISSUE THREAD

**Issue by Kevin-Chant** [growthbook/growthbook-swift#62]
If one of the four operators `$or`, `$nor`, `$and`, or `$not` exists at a particular level of the targeting conditions, all other keys at that level are ignored. This can be worked around by wrapping the level in an `{ $and: [...] }`, but having multiple keys at the same level should be natively supported by the SDK as it's part of the Mongo query language.

See [this pr](https://github.com/growthbook/growthbook/pull/2516/files#diff-debcc522d820069fb37f8383f8e726306fd7b3d0c2eed981870aee179623a262) for an example of fixing this behavior in the JS sdk

**Comment by vazarkevych** [comment]
[The pull request](https://github.com/growthbook/growthbook-swift/pull/63) was created according to this issue.
