### ISSUE TITLE
How can I update the cache in real time without having to refreshCache?

### ISSUE THREAD

**Issue by mattials** [growthbook/growthbook-swift#64]
I am using version 1.0.56, with this initializer:

```
 growthBook = GrowthBookBuilder(
            apiHost: configurationModel.apiHost,
            clientKey: configurationModel.clientKey,
            encryptionKey: configurationModel.encryptionKey,
            attributes: configurationModel.attributes,
            trackingCallback: { experiment, experimentResult in
                print("trackingCallback: \{ experiment):\(experimentResult)”)
            },
            refreshHandler: { isRefreshed in
                print("isRefreshed: \(isRefreshed)”)
            },
            backgroundSync: true).initializer()
````

I would like to know if having the app open and without ever taking out of memory growthBook could update cached parameters, this is necessary to be able to force updates in real time of our application.

**Comment by vazarkevych** [comment]
Hi, @mattials. We will investigate it and get back to you with feedback.

**Comment by vazarkevych** [comment]
Hi, @mattials. After you set backgroundSync to true and handle the value in the refreshHandler, it will work even if you take your app into the background. It will update features, and when you reopen the app, it will call refreshCache.

**Comment by mattials** [comment]
Thank you for your reply!
