### ISSUE TITLE
Disabling a feature in the GrowthBook UI did not also disable features in the application

### ISSUE THREAD

**Issue by august-growthbook** [growthbook/growthbook-swift#67]
Submitting this on behalf of a user:

If no features are sent then the SDK does not recognize that a change has occurred, so the feature array never gets updated. Its probably something that needs to be fixed in the SDK but we can work around it for now by always sending one enabled feature. 

---

The original issue was disabling a feature in the GB UI did not cause the features to be disabled in the application.

> When we debugged the code, we saw that even though the calls to GB were showing that features had changed, the GrowthBookBuilder refreshHandler was still saying refereshed = false. We were wondering if there was some level of cache happening that was preventing the GB SDK from getting the latest state. We gave it over 30 min but the SDK is still not getting the correct refreshed state.

**Comment by vazarkevych** [comment]
Hi, @august-growthbook. We will check that and find a solution.
