### ISSUE TITLE
Force rule based on osVersion not returning correct Value

### ISSUE THREAD

**Issue by kindra-saab** [growthbook/growthbook-swift#68]
I have one feature flag in which I applied one force rule based on osVersion.

I have to check something specifically on OS Version 16.4.
I checked the attributes in my code, we are setting osVersion as "16.4" to growthbook SDK, and force rule also returns this in string format "16.4",  but still SDK is not returning correct value.

Can you guys have a look at this on priority pls.

**Comment by vazarkevych** [comment]
Hi, @kindra-saab. We will check that and write to you.

**Comment by vazarkevych** [comment]
Hi, @kindra-saab. In what format did you receive the value?

**Comment by kindra-saab** [comment]
Hey @vazarkevych , the osVersion value ?

**Comment by vazarkevych** [comment]
Hi, @kindra-saab . Yes osVersion.

**Comment by vazarkevych** [comment]
Hi, @kindra-saab. Did you check osVersion format?

**Comment by kindra-saab** [comment]
Hey @vazarkevych, Its in string format, something like "16.4".

**Comment by kindra-saab** [comment]
<img width="195" alt="Screenshot 2024-08-12 at 3 08 02 PM" src="https://github.com/user-attachments/assets/cfb7307a-658e-4f4b-a469-d87721b0a805">

**Comment by vazarkevych** [comment]
Hi, @kindra-saab. Thank you for providing additional information. We will check it.

**Comment by vazarkevych** [comment]
Hi, @kindra-saab. And what version of SDK are you using?

**Comment by vazarkevych** [comment]
Hi, @kindra-saab. We reviewed your information but were unable to reproduce the bug. The version returns correctly on our end. Could you please provide the steps you took to encounter this issue?

**Comment by vazarkevych** [comment]
We are not able to reproduce the issue on our side.
