### ISSUE TITLE
Enabling/Disabling encryption on GrowthBook UI Fails

### ISSUE THREAD

**Issue by EduardoDeLaCruzMarrero** [growthbook/growthbook-swift#69]
Giving some context...

We had GrowthBook v1.0.48, this version removes rosetta but had an issue related to encryption. We are handling the app force update with a GrowthBook feature flag, we have updated GrowthBook to v1.0.57 and reactivated the encryption. We noticed that our users with our app version using GrowthBook v1.0.48 were not getting the force update alert. When this was reported we realized that they were still with v1.0.48 so the encryption was not supported, then we proceeded to deactivate the encryption again, until all our users migrated to the new version.

The main problem is...

For some reason, It seems that activating the encryption in the GrowthBook web page works, but when we deactivate it again is not truly deactivated because our users with v1.0.48 are still not getting any GrowthBook information on the JSON producing the force update not to be displayed.

**Comment by vazarkevych** [comment]
Hi, @EduardoDeLaCruzMarrero . We will check that and write to you.

**Comment by EduardoDeLaCruzMarrero** [comment]
Hi @vazarkevych  we have backgroundSync as default (false), when we deactivated the encryption, users with version 1.0.57 get information from GrowthBook but those that still with 1.0.48 get nil in the JSON data

**Comment by lakshaysuri13** [comment]
Hi @vazarkevych do we have an update here? We solved a critical bug in the mobile app and without force update we have users still facing the issue. 

Let us know please

Thanks!

**Comment by vazarkevych** [comment]
Hi, @lakshaysuri13. In what data did you receive nil in the JSON data, I mean what request did you get this response nil?

**Comment by vazarkevych** [comment]
Can users update the SDK to version 1.0.57? We can check it in version 1.0.48, but it won't help because the users had a differently configured version of 1.0.48. The only way is to update to the latest SDK, version 1.0.57.

**Comment by EduardoDeLaCruzMarrero** [comment]
It seems to be related to delay persisting the encryption changes I proceed to close the ticket is already working for our users

**Comment by vazarkevych** [comment]
Thank you for the update.
