### ISSUE TITLE
Encrypted features are not parsed, after latest version fix

### ISSUE THREAD

**Issue by sbliatsios** [growthbook/growthbook-swift#72]
After the fix in latest version 1.0.59 [71](https://github.com/growthbook/growthbook-swift/pull/71), with the removal of !features.isEmpty the encrypted features are not parsed, because there is an empty array of features. We need to check if encrypted features also exist. 

Also there is a decoding error in FeaturesViewModel in prepareFeatureData when decoding the FeaturesDataModel. The issue is that the savedGroups property is declared as String? but in fact is a dictionary.

**Comment by Kevin-Chant** [comment]
@vazarkevych could you take a look here (and let me know if you need any help w/ the `savedGroups` part)? I'd jump in but I haven't started learning Swift yet :sweat_smile:

**Comment by vazarkevych** [comment]
Hi, @sbliatsios. Thank you for providing the detailed information. We found an issue, fixed it, and will provide a pull request for it as soon as possible.
